apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  app-config: |
    version: v1
    description: "This is a test configuration for my-app"
    settings:
      - key: "maxConnections"
        value: "100"
      - key: "enableFeatureX"
        value: "true"
